export const routes = {
  login: "/login",
  register: "/register",
  dashboard: "/dashboard",
  courses: "/",
  applyToTeacher: "/apply-to-teacher",
  courseById: (courseId = ":courseId") => `/courses/${courseId}`,
  chapterById: (chapterId = ":chapterId") => `/chapters/${chapterId}`,
  examById: (examId = ":examId") => `/exams/${examId}`,
  myCourses: "/my-courses",
  myCourseById: (courseId = ":courseId") => `/my-courses/${courseId}`,
  profile: "/profile",
  settings: "/settings",
  userById: (userId = ":userId") => `/users/${userId}`,
  help: "/help",
  forgotPassword: "/forgot-password",
  teacherApplication: "/teacher-application",
  users: "/users",
  editChapter: (chapterId: string = ":chapterId") =>
    `/edit-chapter/${chapterId}`,
  createChapter: "/create-chapter",
  editExam: (examId: string = ":examId") => `/edit-exam/${examId}`,
  createExam: "/create-exam",
  courseStatistics: "/course-statistics",
  createCourse: "/create-course",
  profileView: (userId: string = ":userId") => `/profile/${userId}`,
} as const;
