export const routes = {
  login: "/login",
  register: "/register",
  dashboard: "/dashboard",
  courses: "/",
  applyToTeacher: "/apply-to-teacher",
  courseById: (courseId = ":courseId") => `/courses/${courseId}`,
  chapterById: (chapterId = ":chapterId") => `/chapters/${chapterId}`,
  examById: (examId = ":examId") => `/exams/${examId}`,
  myCourses: "/my-courses",
  profile: "/profile",
  settings: "/settings",
  userById: (userId = ":userId") => `/users/${userId}`,
  help: "/help",
  forgotPassword: "/forgot-password",
  teacherApplication: "/teacher-application",
} as const;
